### ISSUE TITLE
Add About page

### ISSUE THREAD

**Issue by Tharanishwaran** [Sensetrons/sensetrons.io#4]
## Description 
 - Add about page to sensetrons.io

**Comment by sivasuriyankumarasamy** [comment]
Hi @Tharanishwaran 

I would like to work on this. Can you assign this issue to me.

**Comment by Tharanishwaran** [comment]
Hi @sivasuriyankumarasamy  thank you go ahead.

**Comment by AkshitBhandariCodes** [comment]
hi i can help you out with this can you assign me this issue

**Comment by Tharanishwaran** [comment]
@AkshitBhandariCodes  thank you go ahead.

**Comment by AkshitBhandariCodes** [comment]
@Tharanishwaran hey i have created a PR plzz check
